#!/usr/local/bin/zsh
# to run from cron, to make sure the wx pages are updating

for i in wx{1..9} wx_0x0a; do
	find "/var/www/htdocs/${i}/data" -mmin -20 |grep . > /dev/null || {
		echo "No new data in wx$i/data in the last 20min!"
	}
done

for j in wx/data wx0/dust_wx/data wx0/power_weather/data wx0/wx/data; do
	find "/var/www/htdocs/${j}" -mmin -20 |grep . > /dev/null || {
		echo "No new data in ${j} in the last 20min!"
	}
done
