#!/bin/sh

test -n "$SSH_ORIGINAL_COMMAND" || exit 1

CMD="rsync --server -logDtpre.iLsfx --stats . /mnt/violet/backups/poptartbk/"

[[ "$SSH_ORIGINAL_COMMAND" == "$CMD" ]] || exit 1

[[ "$SSH_ORIGINAL_COMMAND" == "$CMD" ]] && {
	eval $CMD
	exit $?
}
