#!/bin/ksh
# Script for looking up english words.

(($#==1)) || {
        echo "This script takes one word as an argument."
        exit 1
}

lynx -cookies http://dictionary.reference.com/browse/$1\?jss=0
