#!/bin/sh

(echo P5 500 160 65535; cat pixmap.dat) > pixmap.pgm

test -f co3.png || {
	convert -size 1x600 gradient:'#FFF-#0FF' -set colorspace HSB -colorspace RGB gradient_rainbow_2.png
	convert gradient_rainbow_2.png -crop 1x400+0+200 co3.png
}

convert pixmap.pgm co3.png -interpolate Spline -clut rb_pixmap.png

display rb_pixmap.png
