#!/usr/local/bin/python3
# -*- coding: utf-8 -*-

# this is a script to print out the names of the most recent images from the
# DSCOVR satellite's EPIC camera
# api documented here:
# https://epic.gsfc.nasa.gov/about/api

import argparse, json, sys, urllib.request, uuid

if __name__ == "__main__":

	parser = argparse.ArgumentParser(description='Grab the latest DSCOVR EPIC image name.')

	group = parser.add_mutually_exclusive_group()
	group.add_argument('--enh', dest = 'enh', action = 'store_true', help = 'print the latest enhanced image name')
	group.add_argument('--nat', dest = 'nat', action = 'store_true', help = 'print the latest natural color image name')
	args = parser.parse_args()

	if ((args.enh | args.nat) == 0):
		print("One of ethier --nat or --enh is required.")
		sys.exit(1)

	if (args.enh & args.nat):
		print("This shouldn't happen. Please choose only one of --nat or --enh.")
		sys.exit(1)

	if (args.enh):
		url = 'https://epic.gsfc.nasa.gov/api/enhanced'
	if (args.nat):
		url = 'https://epic.gsfc.nasa.gov/api/natural'

	try:
		urldata = urllib.request.urlopen(url)
	except:
		print("Failed to open url.")
		exit()

	try:
		data = json.loads(urldata.read())
	except:
		print("Failed to parse urldata.")
		exit()

	for i in data:
		latest = i['image']

	#print("https://epic.gsfc.nasa.gov/epic-archive/png/" + latest + ".png")
	print(latest)
