#!/usr/local/bin/zsh

# t_noon[h] = (long + 10.75° / 15[°/h]) + 12[h]
# long = 15[°/h](t[h] - 12[h]) - 10.75°

# only use a diff res for GOES-17 so it has a diff name and then -N works.
earths=( \
# 0°		noon = 12:43z
'https://view.eumetsat.int/geoserver/wms?service=WMS&version=1.3.0&request=GetMap&layers=mtg_fd:rgb_geocolour,mtg_fd:li_afa,backgrounds:ne_10m_coastline,backgrounds:ne_boundary_lines_land&bbox=-5500000,-5500000,5500000,5500000&width=2500&height=2500&srs=AUTO:97004,9001,0,0&styles=&format=image/jpeg&bgcolor=0x000000' \
# 75.2° West	noon = 17:44z
'https://cdn.star.nesdis.noaa.gov/GOES16/ABI/FD/GEOCOLOR/1808x1808.jpg?0' \
# 137.2° West	noon = 21:52z
'https://cdn.star.nesdis.noaa.gov/GOES17/ABI/FD/GEOCOLOR/1808x1808.jpg?1' \
# 219.3° West	noon = 03:20z
'https://rammb.cira.colostate.edu/ramsdis/online/images/latest_hi_res/himawari-8/full_disk_ahi_true_color.jpg' \
# 318.5° West	noon = 09:57z
'https://view.eumetsat.int/geoserver/wms?service=WMS&version=1.3.0&request=GetMap&layers=msg_iodc:rgb_natural,backgrounds:ne_10m_coastline,backgrounds:ne_boundary_lines_land&bbox=-5500000,-5500000,5500000,5500000&width=1800&height=1800&srs=AUTO:97004,9001,45.5,0&styles=&format=image/jpeg&bgcolor=0x000001' \
)

usage() {
	echo "usage: $(basename "$0"): [-hnv]"
	echo -e "\t-h: usage"
	echo -e "\t-n: display the currently sunniest side of earth (follow noon)"
	echo -e "\t-v: verbose"
	exit 1
}

# sats:			  g17    h8     iodc   eu     g16    g17
# sat noon times:	21:52z 03:20z 09:57z 12:43z 17:44z 21:52z
# sat boundry times:	   00:36z 06:38z 11:20z 15:13z 19:48z 00:36z
# 01-07: h8
# 07-12: iodc
# 12-16: eu
# 16-20: g16
# 20-01: g17
noon_pic () {
	DH="$(date +%H)"
	(( $DH >= 01 && $DH < 07 )) && n_pic=$earths[4]
	(( $DH >= 07 && $DH < 12 )) && n_pic=$earths[5]
	(( $DH >= 12 && $DH < 16 )) && n_pic=$earths[1]
	(( $DH >= 16 && $DH < 20 )) && n_pic=$earths[2]
	(( $DH >= 20 && $DH < 24 )) && n_pic=$earths[3]
	(( $DH >= 00 && $DH < 01 )) && n_pic=$earths[3]

	echo "${n_pic}"
}

msg_stamp(){
	wget -qO - "https://view.eumetsat.int/geoserver/wms?service=WMS&version=1.3.0&request=GetCapabilities" | \
		grep -A20 "<Name>msg_iodc:rgb_natural</Name>" | \
		egrep -o 'Dimension name="time" default="[0-9T:-]{19}Z' | \
		sed 's/.*"//'
}

mtg_stamp(){
	wget -qO - "https://view.eumetsat.int/geoserver/wms?service=WMS&version=1.3.0&request=GetCapabilities" | \
		grep -A20 "<Name>mtg_fd:rgb_geocolour</Name>" | \
		egrep -o 'Dimension name="time" default="[0-9T:-]{19}Z' | \
		sed 's/.*"//'
}


loop_wait=120 # 10min / 5 pics
noon_follow=0
verbose=0

[ -e /tmp/sats ] || mkdir /tmp/sats
cd /tmp/sats || exit 1

while getopts hnv OPT; do
        case "$OPT" in
                n) noon_follow=1 ;;
                v) verbose=1 ;;
                h) usage ;;
                *) usage ;;
        esac
done

while true; do
	for pic in $earths; do
		_pic="$(basename "${pic}")"
		[[ $noon_follow == "1" ]] && { pic="$(noon_pic)"; loop_wait=600; }
		[[ $verbose == "0" ]] && wget -qt 2 -T 32 "${pic}" -O "${_pic}"
		[[ $verbose == "0" ]] || wget -t 2 -T 32 "${pic}" -O "${_pic}"

		if [ -s "${_pic}" ]; then
			if [[ "${_pic}" == 'jpeg&bgcolor=0x000000' ]]; then
				mogrify -font DejaVu-Sans -stroke white -fill white -pointsize 36 \
					-annotate +0+2480 "$(mtg_stamp)" "${_pic}"
			elif [[ "${_pic}" == 'jpeg&bgcolor=0x000001' ]]; then
				mogrify -font DejaVu-Sans -stroke white -fill white -pointsize 24 \
					-annotate +0+1780 "$(msg_stamp)" "${_pic}"
			fi

			feh --bg-max "${_pic}"
		fi
		sleep $loop_wait
	done
done
