#!/bin/ksh

HOST_N="$(hostname -s)"

# turn the hdmi/projector off on my thinkpad x220s
[ "${HOST_N}" = 'iva' -o "${HOST_N}" = 'socket' -o "${HOST_N}" = 'bolt' ] && {
	xrandr --output LVDS-1 --auto --output HDMI-1 --off
}

# on sand and dust switch back to laptop display
[ "${HOST_N}" = 'dust' -o "${HOST_N}" = 'sand' ] && {
	xrandr --output eDP-1 --primary --auto --output HDMI-1 --off
}
