#!/bin/bash
# generic raspberry pi backup script
# since we have an nfs mount, just backup there
# don't use rsync -a cuz nfs

HNAME=`hostname -s`
DEST="/import/home/ghz/pi_backups/${HNAME}/"

test -d /import/home/ghz/pi_backups || {
	echo "can't find nfs dir"
	exit 1
}

test -d $DEST || mkdir $DEST

test -d $DEST || {
	echo "can't find our nfs backup dir"
	exit 1
}

time /usr/bin/rsync -e "ssh -q" -rlpDh --stats \
/boot /home /etc /root /var/spool/cron/crontabs/ $DEST
