#!/bin/sh

# scratch script rev0 to remind me where to get this damn file.
# todo: write correctly

URL='http://ftp.de.debian.org/debian/pool/main/i/igerman98/wngerman_20161207-11_all.deb'

TMPDIR=`mktemp -d /tmp/ng.XXXXXXXXXX`
cd $TMPDIR || exit 1
wget "${URL}"
dd if="$(basename "${URL}")" of=second.tar.xz skip=1876 bs=1
unxz second.tar.xz
tar xvf second.tar ./usr/share/dict/ngerman
cp $TMPDIR/usr/share/dict/ngerman ./
