#!/bin/sh

# a scripted collection of notes and such for when i find myself on linux boxes

apt install zsh fvwm imagemagick firefox-esr moreutils net-tools xorg-dev xinit git unzip xplanet vim x11-apps x11-xserver-utils ksh xterm xidle xscreensaver  xscreensaver-data  xscreensaver-data-extra xscreensaver-gl xscreensaver-gl-extra nmap locate lynx lsof bsd-mailx

dpkg-reconfigure tzdata

systemctl set-default multi-user.targe
