#!/bin/sh

# a scripted collection of notes and such for when i find myself on linux boxes

apt install zsh fvwm imagemagick firefox-esr moreutils net-tools xorg-dev xinit git unzip xplanet vim x11-apps x11-xserver-utils ksh xterm xidle xscreensaver  xscreensaver-data  xscreensaver-data-extra xscreensaver-gl xscreensaver-gl-extra nmap locate lynx lsof bsd-mailx binutils openntpd alsa-utils figlet upower suckless-tools tcpdump xinput rsync xpdf

# in case of radio
apt install fldigi ipython ipython3

dpkg-reconfigure tzdata

systemctl set-default multi-user.target

# tf?
alsactl init

ln -s /usr/bin/zsh /usr/local/bin/zsh
ln -s /usr/bin/xplanet /usr/local/bin/xplanet

################ notes ################

# in case of weird colors stuck on
# echo -e "\033[0m;"

# this should suspend
# systemctl suspend
