#!/bin/sh

# a scripted collection of notes and such for when i find myself on linux boxes

# add normal unix things
apt install moreutils net-tools xorg-dev xinit xplanet x11-apps x11-xserver-utils ksh xterm xidle nmap locate lynx lsof bsd-mailx binutils openntpd alsa-utils figlet upower suckless-tools tcpdump xinput rsync strace whois build-essential manpages-dev tmux

# add packages
apt install zsh fvwm imagemagick firefox-esr git unzip vim xpdf

# in case of radio
apt install fldigi ipython ipython3 xastir
usermod -aG dialout ghz

dpkg-reconfigure tzdata

systemctl set-default multi-user.target

echo 'kernel.dmesg_restrict=0' >> /etc/sysctl.d/local.conf
systemctl kernel.dmesg_restrict=0

# tf?
alsactl init

ln -s /usr/bin/zsh /usr/local/bin/zsh
ln -s /usr/bin/xplanet /usr/local/bin/xplanet

# this hopefully winds up in the [Login] section of this file.
# as of this wrting [Login] is the only section of this file.
echo 'HandleLidSwitch=ignore' >> /etc/systemd/logind.conf
echo 'HandleLidSwitchDocked=ignore' >> /etc/systemd/logind.conf
systemctl restart systemd-logind.service

################ notes ################

# in case of weird colors stuck on
# echo -e "\033[0m;"

# this is the amazing user friendly way brightness is done.
# why the damn kb keys don't just work out of the box i don't know.
# cat /sys/class/backlight/intel_backlight/brightness
# echo 2000 > /sys/class/backlight/intel_backlight/brightness

# this should suspend
# systemctl suspend
