#!/bin/ksh
# this is a list of the stuff i most often do after a new OpenBSD install
# scriptified so i can be _even_ _lazier_

usage() {
	echo "usage: $0: laptop|server|workstation|pi username"
	exit 1
}

(($#==2)) || usage

[[ "${1}" == "laptop" || "${1}" == "server" || "${1}" == "workstation" || "${1}" == "pi" ]] || usage

id "${2}"> /dev/null || usage

[[ "${1}" == "laptop" || "${1}" == "workstation" ]] && {
	pkg_add wget git firefox ImageMagick nmap rsync-- vim--no_x11 figlet zsh xplanet \
	avr-binutils avr-libc avr-gcc avr-gdb bzip2 curl magicpoint texlive_texmf-full unzip-- \
	feh mplayer geeqie ipython3 xpdf ansible graphviz aspell-de lynx py3-matplotlib fvwm2 \
	got mutt-- noto-cjk slock xmem
	
	[[ "${1}" == "laptop" ]] && {
		rcctl enable apmd
		rcctl set apmd flags -A

		echo "machdep.lidaction=0" >> /etc/sysctl.conf
	}

	# needs us a few more ptys.
	zsh -c "cd /dev && sh ./MAKEDEV pty{0..15}"
}

[[ "${1}" == "server" ]] && {
	# vim for UTF-8 support
	pkg_add wget git nmap rsync-- vim--no_x11 figlet zsh bzip2 curl

	# dhcpleased and slaacd don't do anything w.o. an IF marked AUTO,
	# but start with the assumption that we don't need them if our IFs are static
	# and that our upstream routers are dumb/hostile and give us garbage if our IFs are AUTO.
	# the later often being the case with many of the local providers, which is why we
	# turn off resolvd as well.
	rcctl disable sndiod resolvd dhcpleased slaacd
}

[[ "${1}" == "pi" ]] && {
	pkg_add wget git nmap rsync-- vim--no_x11 figlet zsh bzip2 curl gnuplot-- \
	lynx got ipython3 aspell-de

	echo -e "\n# updates" >> /var/cron/tabs/root
	echo -e "~\t~\t*\t*\t5\tsysupgrade" >> /var/cron/tabs/root
}

rcctl disable check_quotas

echo "keyboard.repeat.del1=150" >> /etc/wsconsctl.conf
echo "keyboard.repeat.deln=50" >> /etc/wsconsctl.conf

usermod -G dialer "${2}"
echo "${2}" > /root/.forward
echo "set ${2}'s .forward"

chsh -s /usr/local/bin/zsh "${2}"

(uname -a ; figlet `hostname -s` ; echo) > /etc/motd
echo '(uname -a; hostname -s | /usr/local/bin/figlet) > /etc/motd' >> /etc/rc.local

# no root console logins
sed -i 's/secure//' /etc/ttys

# i like my visual host key fingerprints
sed -i 's/#   VisualHostKey no/VisualHostKey yes/' /etc/ssh/ssh_config

# don't really need a log full of "syslog restarted"
sed -i 's/syslog,/syslog.notice,/' /etc/syslog.conf

# enable soft dependencies on non-root, non-swap file systems
# softdep's have gone away for the time being
# sed -i 's/ 1 2/,softdep 1 2/g' /etc/fstab

# almost straight out of install.site(5)
# runs syspatch twice, incase it needs to patch itself first
cat <<- EOF >> /upgrade.site
	echo 'syspatch' >> /etc/rc.firsttime
	echo 'syspatch' >> /etc/rc.firsttime
	echo 'pkg_add -IVvum' >> /etc/rc.firsttime
EOF
chmod +x /upgrade.site

echo -e "~\t~\t*\t*\t*\tpkg_add -u" >> /var/cron/tabs/root
echo -e "~\t*/8\t*\t*\t*\tsyspatch" >> /var/cron/tabs/root
rcctl restart cron
