#!/bin/sh

# this is the server version

pkg_add wget git nmap rsync-- vim--no_x11 figlet zsh bzip2 curl

rcctl set ntpd flags -s
rcctl disable sndiod
echo "check_quotas=NO" >> /etc/rc.conf.local

echo "keyboard.repeat.del1=150" >> /etc/wsconsctl.conf
echo "keyboard.repeat.deln=50" >> /etc/wsconsctl.conf

usermod -G dialer ghz

(uname -a ; figlet `hostname -s` ; echo) > /etc/motd

# no root console logins
sed -i 's/secure//' /etc/ttys
