#!/bin/sh

pkg_add wget git firefox ImageMagick nmap rsync--iconv vim--no_x11 figlet zsh xplanet avr-binutils avr-libc avr-gcc avr-gdb bzip2 curl magicpoint texlive_texmf-full unzip-- ssvnc feh mplayer geeqie ipython xpdf ansible graphviz evince--light aspell-de lynx py-matplotlib fvwm2

rcctl enable ntpd
rcctl set ntpd flags -s
rcctl enable apmd
rcctl set apmd flags -A

echo "machdep.lidaction=0" >> /etc/sysctl.conf

echo "keyboard.repeat.del1=150" >> /etc/wsconsctl.conf
echo "keyboard.repeat.deln=50" >> /etc/wsconsctl.conf

usermod -G dialer ghz

(uname -a ; figlet `hostname -s` ; echo) > /etc/motd

# needs us a few more ptys.
cd /dev && sh MAKEDEV pty[q-z][0-9a-zA-Z]

# no root console logins
sed -i 's/secure//' /etc/ttys

# i like my visual host keys
sed -i 's/#   VisualHostKey no/VisualHostKey yes/' /etc/ssh/ssh_config
