#!/bin/sh

# this is the server version

pkg_add wget git nmap rsync--iconv vim--no_x11 figlet zsh bzip2 curl

rcctl disable sndiod
echo "check_quotas=NO" >> /etc/rc.conf.local

echo "keyboard.repeat.del1=150" >> /etc/wsconsctl.conf
echo "keyboard.repeat.deln=50" >> /etc/wsconsctl.conf

usermod -G dialer ghz

(uname -a ; figlet `hostname -s` ; echo) > /etc/motd
echo '(uname -a; hostname -s |figlet) > /etc/motd' >> /etc/rc.local

# no root console logins
sed -i 's/secure//' /etc/ttys

# i like my visual host keys
sed -i 's/#   VisualHostKey no/VisualHostKey yes/' /etc/ssh/ssh_config
