#!/usr/local/bin/zsh

while true; do
	LAST_CALL="$(tail -20 ~/.local/share/WSJT-X/ALL.TXT | grep CQ | tail -1 | awk '{print $9}')"
	[[ "${LAST_CALL}" == 'DC7EJT' ]] || {
		grep "${LAST_CALL}" ~/.local/share/WSJT-X/wsjtx.log || {
			echo "${LAST_CALL}"
			for i in 1 2 3; do beep -f 2600 -l 50; done
		}
	}
	sleep 8
done
