#!/bin/ksh

usage() {
	echo "usage: $0: laptop|server username"
	exit 1
}

(($#==2)) || usage

[[ "${1}" == "laptop" || "${1}" == "server" ]] ||  usage

id "${2}"> /dev/null || usage

[[ "${1}" == "laptop" ]] && {
	pkg_add wget git firefox ImageMagick nmap rsync--iconv vim--no_x11 figlet zsh xplanet \
	avr-binutils avr-libc avr-gcc avr-gdb bzip2 curl magicpoint texlive_texmf-full unzip-- \
	ssvnc feh mplayer geeqie ipython xpdf ansible graphviz evince--light aspell-de lynx \
	py-matplotlib fvwm2
	
	rcctl enable apmd
	rcctl set apmd flags -A

	echo "machdep.lidaction=0" >> /etc/sysctl.conf

	# needs us a few more ptys.
	zsh -c "cd /dev && sh ./MAKEDEV pty{0..15}"
}

[[ "${1}" == "server" ]] && {
	pkg_add wget git nmap rsync--iconv vim--no_x11 figlet zsh bzip2 curl

	rcctl disable sndiod
	rcctl disable resolvd
	rcctl disable dhcpleased
}

rcctl disable check_quotas

echo "keyboard.repeat.del1=150" >> /etc/wsconsctl.conf
echo "keyboard.repeat.deln=50" >> /etc/wsconsctl.conf

usermod -G dialer "${2}"

(uname -a ; figlet `hostname -s` ; echo) > /etc/motd
echo '(uname -a; hostname -s |figlet) > /etc/motd' >> /etc/rc.local

# no root console logins
sed -i 's/secure//' /etc/ttys

# i like my visual host keys
sed -i 's/#   VisualHostKey no/VisualHostKey yes/' /etc/ssh/ssh_config

# don't really need a log full of "syslog restarted"
sed -i 's/syslog.info/syslog.notice/' /etc/syslog.conf

# almost straight out of install.site(5)
cat <<- EOF >> /upgrade.site
	echo 'pkg_add -Iu' >> /etc/rc.firsttime
	echo 'syspatch' >> /etc/rc.firsttime
EOF
chmod +x /upgrade.site
