#!/bin/sh

echo "$0[$$]: checking for patches..."

restart_daemons() {
	echo "\n$0[$$]: patches detected, restarting daemons"

	echo "/usr/sbin/rcctl restart smtpd" | /usr/bin/at now +1 min

	/usr/sbin/rcctl restart sshd
	/usr/sbin/rcctl restart httpd
	/usr/sbin/rcctl restart unwind
	# /usr/sbin/rcctl restart nsd
	# /usr/sbin/rcctl restart unbound
}

# is there a better way to tell if a daemon need restarting?
SP_OUT="$(/usr/sbin/syspatch 2>&1 )" && [ ! -z "${SP_OUT}" ] && { echo "${SP_OUT}"; restart_daemons; }
