#!/usr/local/bin/python3

from datetime import datetime, timedelta
from astral import LocationInfo
from astral.sun import sun

ber = LocationInfo("Berlin", "Germany", "Europe/Berlin", 52.529, 13.475)
ber_sun = sun(ber.observer, datetime.now(), tzinfo=ber.timezone)
ber_sun_y = sun(ber.observer, datetime.now() - timedelta(days=1), tzinfo=ber.timezone)

# total daytime
dt = (ber_sun["sunset"] - ber_sun["sunrise"])
dt_h = int(dt.seconds / 3600)
dt_min = int(dt.seconds % 3600 / 60)
dt_sec = dt.seconds - dt_h * 3600 - dt_min * 60

# total daytime yesterday
dt_y = (ber_sun_y["sunset"] - ber_sun_y["sunrise"])

# change in daytime since yesterday
del_dt = dt.seconds - dt_y.seconds
del_dt_min = abs(int(del_dt / 60))
del_dt_sec = abs(del_dt) % 60
if del_dt:
	del_dt_min = del_dt_min * (abs(del_dt) / del_dt)

print("Sun Data for Berlin:")
print("Sunrise:\t", ber_sun["sunrise"].strftime("%F %T%Z"))
print("Sunset:\t\t", ber_sun["sunset"].strftime("%F %T%Z"))
print("Daylength:\t", dt_h, "hours", dt_min, "min", dt_sec, "sec")
print("Δ Daylength:\t {:.0f} min {:.0f} sec".format(del_dt_min, del_dt_sec))
