#!/bin/sh
# this is totally untested at this point. it will be more baked when i get another
# rpi to test it on.

set -e

HNAME=`hostname -s`

[ $HNAME = "raspberrypi" ] && {
	echo "set hostanme"
	exit 1
}

apt-get update
apt-get install -y git nfs-common boinc-client zsh figlet rsync ganglia-monitor bsd-mailx locate
apt-get upgrade


userdel pi
uesradd -d /import/home/ghz -s `which zsh` -u 1000 -g 1000 \
-G ghz,adm,dialout,cdrom,sudo,audio,video,plugdev,games,users,input,netdev,gpio,i2c,spi ghz

mkdir -p /import/home/ghz
chown ghz:ghz /import/home/ghz
echo -e krtek:/mnt/violet/pi/ghz\\t/import/home/ghz\\tnfs\\trw\\t0\\t0 >> /etc/fstab
update-rc.d rpcbind enable
update-rc.d nfs-common enable
service rpcbind start
service nfs-common start
mount -a

figlet $HNAME > /etc/motd

echo ghz@darkdata.org > /root/.forward

service ganglia-monitor restart

install -o root -g root -m 600 /import/home/ghz/env/rpi/root_crontab /var/spool/cron/crontabs/root
mkdir /root/scripts/
sed "s+HHHHHH+$HNAME+g" /import/home/ghz/scripts/gen_pi_bk > /root/scripts/gen_pi_bk
cp /import/home/ghz/scripts/netcheck /root/scripts/

ssh-keygen -t ed25519 -f "$HOME/.ssh/${HNAME}.backup" -N "" -C "${HNAME}_backup_key"

sudo -u ghz /import/home/ghz/pi_setup/ghz_script

reboot
