# vim:set tabstop=2 softtabstop=2 shiftwidth=2 expandtab:
---
- hosts: pis
  gather_facts: no
  user: root

  tasks:

  - name: restart ganglia
    service:
      name: ganglia-monitor
      state: restarted
    when: inventory_hostname != "muffin"
