#!/usr/bin/perl -T
use strict;
use warnings;
use utf8;
use open qw(:std :utf8);
use Encode qw(encode decode);

# Thanks to Mike Muuss for the math ;)

my ($num, $tsumsq, $tsum, $ded, $thresmul) = (0, 0, 0, 0, 3.0);
my @dat;

@ARGV = map { decode("UTF-8", $_) } @ARGV;

while(<>) {
	chomp;
	my ($x, $y) = split;
	if ($y ne "??") {
		push @dat, [ $x, $y ];
		$num++;
		$tsum += $y;
		$tsumsq += ($y * $y);
	} else {
		push @dat, [ $x, $y ];
		$ded++;
	}
}

if ($num <= 0) {
        exit(1);
}

my $avg = $tsum / $num;
my $dev = sqrt($tsumsq / $num - $avg * $avg); 
my $thresh = $dev * $thresmul;

for (my $j = 0; $j < ($num + $ded); $j++) {
	if ($dat[$j][1] ne "??"){
		if (abs( $dat[$j][1] - $avg ) > $thresh){
			$dat[$j][1] = "??";
		}
	}
	print $dat[$j][0], " ", $dat[$j][1], "\n";
}
