#!/usr/bin/perl -T
use strict;
use warnings;
use utf8;
use open qw(:std :utf8);
use Encode qw(encode decode);

# produce general statistics on data from stdin
# often used with my weather data, but then i found i used it for any file
# with data in the following format:
# datetime	data
# which i run across often for some reason. so this script is here too

#Thanks to Mike Muuss for the math ;)

my ($num, $tsumsq, $tsum, $max) = (0, 0, 0, 0);
my $min = 9999999;
my $threshmul = 4.0;

@ARGV = map { decode("UTF-8", $_) } @ARGV;

while(<>){
	chomp;
	my ($x, $y) = split;
	if($y ne "??"){
		$num++;
		$tsum += $y;
		$tsumsq += ($y * $y);
		if($y > $max){ $max = $y; }
		if($y < $min){ $min = $y; }
	}
}

my $avg = $tsum / $num;
my $dev = sqrt($tsumsq / $num - $avg * $avg); 
my $thresh = $dev * $threshmul;

print	"Num:\t\t", $num, "\n";
print	"Tsum:\t\t", $tsum, "\n";
print	"Tsumsq:\t\t", $tsumsq, "\n";
printf	"Avg:\t\t%.2f\n", $avg;
printf	"std-dev:\t%.2f\n", $dev;
printf	"Thresh:\t\t%.2f\n", $thresh;
print	"ThreshMul:\t", $threshmul, "\n";
print	"Min:\t\t", $min, "\n";
print	"Max:\t\t", $max, "\n";
printf	"Avg - Thresh:\t%.2f\n", $avg - $thresh;
printf	"Avg + Thresh:\t%.2f\n", $avg + $thresh;
