# vim:set tabstop=2 softtabstop=2 shiftwidth=2 expandtab:

# this is only for setting up little weather probes from raspberry pi zero w's
# it is very similar to the rpi_initial_setup.yml. this needs to be refactored.
# that's a project for later
---
- hosts: wxps
  gather_facts: no
  user: root

  tasks:

  - name: update, upgrade
    apt:
      upgrade: full
      update_cache: yes
    tags:
      - update

  - name: add packages
    apt:
      name: '{{ item }}'
      state: present
    with_items:
      - git
      - zsh
      - figlet
      - rsync
      - bsd-mailx
      - locate
      - vim
      - postfix
      - ufw
    tags:
      - update
      - packages

  - name: disable silly services
    systemd:
      name: '{{ item }}'
      state: stopped
      enabled: no
    with_items:
      - bluetooth
      - hciuart

  - name: blacklist bt modules
    kernel_blacklist:
      name: '{{ item }}'
      state: absent
    with_items:
      - btbcm
      - hci_uart
      - bnep
      - bluetooth

  - name: pull bt modules
    modprobe:
      name: '{{ item }}'
      state: absent
    with_items:
      - hci_uart
      - btbcm
      - bnep
      - bluetooth

  - name: pull pi user if it's still there
    user:
      name: pi
      state: absent

  - name: pull pi group if it exists
    group:
      name: pi
      state: absent

  - name: add me group
    group:
      name: ghz
      state: present

  - name: add me
    user:
      name: ghz
      uid: 1000
      home: /home/ghz
      group: ghz
      groups: adm,dialout,cdrom,sudo,audio,video,plugdev,games,users,input,netdev,gpio,i2c,spi
      shell: /usr/bin/zsh

  - name: add .forward
    lineinfile:
      dest: /root/.forward
      create: yes
      line: ghz@darkdata.org
      owner: root
      group: root
      mode: 0644

  - name: add figlet hostname to motd
    shell: figlet `hostname -s` > /etc/motd

  - name: add root scripts dir
    file:
      path: /root/scripts
      owner: root
      group: root
      state: directory
      mode: 0755

  - name: template backup script
    template:
      src: /home/ghz/scripts/gen_pi_bk
      dest: /root/scripts/gen_pi_bk
      owner: root
      group: root
      mode: 0755

  - name: template netcheck script
    template:
      src: /home/ghz/scripts/netcheck
      dest: /root/scripts/netcheck
      owner: root
      group: root
      mode: 0755

  - name: add path to crontab
    cron:
      env: yes
      name: PATH
      value: /bin:/sbin:/usr/bin:/usr/sbin:/usr/local/bin:/usr/local/sbin

  - name: add netcheck cron entry
    cron:
      name: netcheck
      minute: "*/13"
      hour: "*"
      day: "*"
      weekday: "*"
      month: "*"
      user: root
      job: "/root/scripts/netcheck"

  - name: add backup cron job
    cron:
      name: backup
      # wait for ansible 2.3?
      # minute: "{{ 59 | random(seed=inventory_hostname)) }}"
      # from https://ansibledaily.com/idempotent-random-number/
      minute: "{{ ( inventory_hostname | hash | list | map('int',0,16) | sum ) % 60 }}"
      hour: "{{ (( inventory_hostname | hash | list | map('int',0,16) | sum ) % 5) }}"
      day: "*"
      weekday: "*"
      month: "*"
      user: root
      job: "/root/scripts/gen_pi_bk"

  - name: turn off hdmi to save power
    lineinfile:
      dest: /etc/rc.local
      insertbefore: 'exit 0'
      line: /usr/bin/tvservice -o

  - name: allow port 22
    ufw:
      state: enabled
      rule: allow
      port: 22
      proto: tcp

  - name: set timezone to utc
    timezone:
      name: UTC
